name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "185.114.78.230"
UUID = "211ccd24-3bfe-4f16-8939-77dfd74fedb7"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
